CREATE TABLE PRODUCTS (
	PRODUCT_ID Number(6), 
    TITLE Varchar2(50), 
    DESCRIPTION Varchar2(200), 
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID)
);


CREATE TABLE PROD_OPTIONS (
    PROD_OPTION_ID Number(6), 
    OPTION_NAME Varchar2(50),
    OPTION_VALUE Varchar2(50),
    CONSTRAINT PROP_PK PRIMARY KEY (PROD_OPTION_ID)
);

CREATE TABLE SUBCATEGORIES (
    SUBCATEGORY_ID Number(6), 
    DESCRIPTION Varchar2(60), 
    CONSTRAINT SUBCATEGORIES_PK PRIMARY KEY (SUBCATEGORY_ID)
);

CREATE TABLE SUB_OPTIONS (
    SUB_OPTION_ID Number(6), 
    SUBCATEGORY_ID Number(6), 
    PROD_OPTION_ID Number(6), 
    CONSTRAINT SUOP_PK PRIMARY KEY (SUB_OPTION_ID),
    CONSTRAINT SUBC_SUOP_FK FOREIGN KEY (SUBCATEGORY_ID) REFERENCES SUBCATEGORIES(SUBCATEGORY_ID),
    CONSTRAINT PROP_SUOP_FK FOREIGN KEY (PROD_OPTION_ID) REFERENCES PROD_OPTIONS(PROD_OPTION_ID)
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID Number(6), 
    DESCRIPTION Varchar2(60),
    SUBCATEGORY_ID Number(6), 
    CONSTRAINT CATEGORIES_PK PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT SUBC_CATE_FK FOREIGN KEY (SUBCATEGORY_ID) REFERENCES SUBCATEGORIES(SUBCATEGORY_ID)
);

CREATE TABLE CAT_OPTIONS (
    CAT_OPTION_ID Number(6), 
    CATEGORY_ID Number(6), 
    PROD_OPTION_ID Number(6), 
    CONSTRAINT CAOP_PK PRIMARY KEY (CAT_OPTION_ID),
    CONSTRAINT CATE_CAOP_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT PROP_CAOP_FK FOREIGN KEY (PROD_OPTION_ID) REFERENCES PROD_OPTIONS(PROD_OPTION_ID)
);

CREATE TABLE PROD_CATEGORIES (
    PROD_CATEGORY_ID Number(6),
    PRODUCT_ID Number(6),
    CATEGORY_ID Number(6), 
    CONSTRAINT PRCA_PK PRIMARY KEY (PROD_CATEGORY_ID),
    CONSTRAINT PROD_PRCA_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CATE_PRCA_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE PROD_VARIATIONS (
    PROD_VARIATION_ID Number(6),
    PRODUCT_ID Number(6),
    PRICE Number(6, 2),
    PROD_OPTION_ID Number(6), 
    CUST_OPT_NAME Varchar2(50),
    CUST_OPT_VALUE Varchar2(50),
    CONSTRAINT PRVA_PK PRIMARY KEY (PROD_VARIATION_ID),
    CONSTRAINT PROD_PRVA_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT PROP_PRVA_FK FOREIGN KEY (PROD_OPTION_ID) REFERENCES PROD_OPTIONS(PROD_OPTION_ID)
)

-- Data
INSERT INTO PRODUCTS VALUES (1, 'Laptop', 'Description for Laptop');
INSERT INTO PRODUCTS VALUES (2, 'Chair', 'Description for Chair');
INSERT INTO PRODUCTS VALUES (3, 'Table', 'Description for Table');
INSERT INTO PRODUCTS VALUES (4, 'Phone', 'Description for Phone');
INSERT INTO PRODUCTS VALUES (5, 'Camera', 'Description for Camera');
INSERT INTO PRODUCTS VALUES (6, 'Shoes', 'Description for Shoes');
INSERT INTO PRODUCTS VALUES (7, 'Guitar', 'Description for Guitar');
INSERT INTO PRODUCTS VALUES (8, 'Watch', 'Description for Watch');
INSERT INTO PRODUCTS VALUES (9, 'Headphones', 'Description for Headphones');
INSERT INTO PRODUCTS VALUES (10, 'Book', 'Description for Book');

INSERT INTO PROD_OPTIONS VALUES (1, 'Processor', 'Intel Core i7');
INSERT INTO PROD_OPTIONS VALUES (2, 'RAM', '16GB');
INSERT INTO PROD_OPTIONS VALUES (3, 'Storage', '512GB SSD');
INSERT INTO PROD_OPTIONS VALUES (4, 'Material', 'Wood');
INSERT INTO PROD_OPTIONS VALUES (5, 'Color', 'Red');
INSERT INTO PROD_OPTIONS VALUES (6, 'Style', 'Armchair');
INSERT INTO PROD_OPTIONS VALUES (7, 'Material', 'Wood');
INSERT INTO PROD_OPTIONS VALUES (8, 'Color', 'Brown');
INSERT INTO PROD_OPTIONS VALUES (9, 'Operating System', 'Android');
INSERT INTO PROD_OPTIONS VALUES (10, 'Storage', '128GB');
INSERT INTO PROD_OPTIONS VALUES (11, 'Screen Size', '6.2 inches');
INSERT INTO PROD_OPTIONS VALUES (12, 'Resolution', '20MP');
INSERT INTO PROD_OPTIONS VALUES (13, 'Sensor Type', 'CMOS');
INSERT INTO PROD_OPTIONS VALUES (14, 'Material', 'Leather');
INSERT INTO PROD_OPTIONS VALUES (15, 'Size', '10');
INSERT INTO PROD_OPTIONS VALUES (16, 'Type', 'Electric Guitar');
INSERT INTO PROD_OPTIONS VALUES (17, 'Color', 'Sunburst');
INSERT INTO PROD_OPTIONS VALUES (18, 'Number of Strings', '6');
INSERT INTO PROD_OPTIONS VALUES (19, 'Style', 'Analog');
INSERT INTO PROD_OPTIONS VALUES (20, 'Water Resistance', '30 meters');
INSERT INTO PROD_OPTIONS VALUES (21, 'Type', 'Over-Ear');
INSERT INTO PROD_OPTIONS VALUES (22, 'Color', 'Black');
INSERT INTO PROD_OPTIONS VALUES (23, 'Wireless', 'Bluetooth 5.0');
INSERT INTO PROD_OPTIONS VALUES (24, 'Genre', 'Fiction');
INSERT INTO PROD_OPTIONS VALUES (25, 'Author', 'John Doe');
INSERT INTO PROD_OPTIONS VALUES (26, 'Processor', 'Intel Core i9');
INSERT INTO PROD_OPTIONS VALUES (27, 'RAM', '32GB');
INSERT INTO PROD_OPTIONS VALUES (28, 'Storage', '1TB NVMe SSD');
INSERT INTO PROD_OPTIONS VALUES (29, 'Material', 'Oak Wood');
INSERT INTO PROD_OPTIONS VALUES (30, 'Color', 'Blue');
INSERT INTO PROD_OPTIONS VALUES (31, 'Style', 'Recliner');
INSERT INTO PROD_OPTIONS VALUES (32, 'Material', 'Metal');
INSERT INTO PROD_OPTIONS VALUES (33, 'Color', 'Silver');
INSERT INTO PROD_OPTIONS VALUES (34, 'Operating System', 'iOS 15');
INSERT INTO PROD_OPTIONS VALUES (35, 'Storage', '256GB');
INSERT INTO PROD_OPTIONS VALUES (36, 'Screen Size', '6.7 inches');
INSERT INTO PROD_OPTIONS VALUES (37, 'Resolution', '24MP');
INSERT INTO PROD_OPTIONS VALUES (38, 'Sensor Type', 'CMOS');
INSERT INTO PROD_OPTIONS VALUES (39, 'Material', 'Leather');
INSERT INTO PROD_OPTIONS VALUES (40, 'Size', '12');
INSERT INTO PROD_OPTIONS VALUES (41, 'Type', 'Electric Guitar');
INSERT INTO PROD_OPTIONS VALUES (42, 'Color', 'Sunburst');
INSERT INTO PROD_OPTIONS VALUES (43, 'Number of Strings', '7');
INSERT INTO PROD_OPTIONS VALUES (44, 'Style', 'Analog');
INSERT INTO PROD_OPTIONS VALUES (45, 'Water Resistance', '50 meters');
INSERT INTO PROD_OPTIONS VALUES (46, 'Type', 'Over-Ear');
INSERT INTO PROD_OPTIONS VALUES (47, 'Color', 'Black');
INSERT INTO PROD_OPTIONS VALUES (48, 'Wireless', 'Bluetooth 5.2');
INSERT INTO PROD_OPTIONS VALUES (49, 'Genre', 'Science Fiction');
INSERT INTO PROD_OPTIONS VALUES (50, 'Author', 'Jane Smith');